server:
  port: 9092

spring:
  application:
    name: ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: dubbo-auth
    qos-enable: false
  consumer:
    timeout: 20000
    check: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    username: nacos
    password: nacos
