server:
  port: 9092

spring:
  application:
    name: ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: dubbo-auth
    qos-enable: false
  consumer:
    timeout: 20000
    check: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    username: nacos
    password: nacos

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8088/xxl-job-admin
    executor:
      appName: ums-job
      address:
      ip:
      port: 9990
      logpath:
      logretentiondays: 30
